apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component--hpma
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component--hpma
    app.kubernetes.io/part-of: test-app-fesc
  name: test-component--hpma
  namespace: build-templates-e2e
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: test-component--hpma
status:
  loadBalancer: {}
